include:
  - project: softwareradiosystems/testing-tools
    ref: "11"
    file: .gitlab/ci-shared/workflow.yml
  - project: softwareradiosystems/testing-tools
    ref: "11"
    file: .gitlab/ci-shared/scheduler.yml
  - project: softwareradiosystems/testing-tools
    ref: "11"
    file: .gitlab/ci-shared/versions.yml
  - project: softwareradiosystems/testing-tools
    ref: "11"
    file: .gitlab/ci-shared/default.yml
  - local: .gitlab/ci/build.yml

stages:
  - ci check
  - static
  - build
  - tests
  - scheduler
  - build and publish doc
  - notify status

################################################################################
## CI check
################################################################################
check-ci-versions:
  stage: ci check
  image: registry.gitlab.com/softwareradiosystems/testing-tools/srs-tools:$SRS_TOOLS_VERSION
  rules:
    - if: $ON_MR
  script:
    - ci-version-check --check-main .gitlab-ci.yml --check-directory .gitlab
  dependencies: []

auto rebaser:
  stage: ci check
  rules:
    - if: $ON_DEFAULT_BRANCH
  image: registry.gitlab.com/softwareradiosystems/testing-tools/srs-tools:$SRS_TOOLS_VERSION
  script:
    - gitlab-rebaser --token ${CODEBOT_TOKEN} --namespace ${CI_PROJECT_NAMESPACE} --project ${CI_PROJECT_NAME} --target dev

################################################################################
## Static
################################################################################
.static:
  image: registry.gitlab.com/softwareradiosystems/testing-tools/static_validator:$DOCKER_STATIC_VERSION
  stage: static
  rules:
    - if: $ON_MR
  variables:
    GIT_DEPTH: 0

code-format:
  extends: .static
  script:
    - run-clang-format-diff.sh $CI_MERGE_REQUEST_DIFF_BASE_SHA
    - hex2lowercase.sh
    - is-pristine-repo.sh
  artifacts:
    paths:
      - clang-format.patch
    when: on_failure

include-guards:
  extends: .static
  script:
    - |
      EXIT_CODE=0
      AUTOCORRECTION=1 PRAGMA=1 TARGET_BRANCH=origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME INPUT_PATH="include/srsgnb" INPUT_IGNORE="/bundled/" include-guards-check.sh || EXIT_CODE=$?
      AUTOCORRECTION=1 PRAGMA=1 TARGET_BRANCH=origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME INPUT_PATH="." INPUT_IGNORE="^include/.*" include-guards-check.sh || EXIT_CODE=$?
      is-pristine-repo.sh || EXIT_CODE=$?
      exit $EXIT_CODE

no-binaries-added:
  extends: .static
  script:
    - check-for-added-binaries.sh $CI_MERGE_REQUEST_DIFF_BASE_SHA
  allow_failure: true

################################################################################
## Build + Unit Tests + Integration tests
################################################################################
.alternative builds:
  stage: build
  needs: []
  variables:
    check_flags: "false"
    run_tests: "true"
    enable_coverage: "false"
    coverage_full_report: "false"
  trigger:
    include: .gitlab/ci/build.yml
    strategy: depend

alternative builds:
  extends: .alternative builds
  rules:
    - if: $ON_MR
      variables:
        run_tests: "false"
    - if: $ON_SCHEDULE
  parallel:
    matrix:
      - os_type: ubuntu
        os_version: "22.04"
        compiler: clang
        uhd_version: "4.1.0.5"
      - os_type: ubuntu
        os_version: "20.04"
        uhd_version: "3.15.0.0"
        compiler: [gcc, clang]
      - os_type: archlinux
        os_version: latest
        uhd_version: "4.2.0.0"
        compiler: [gcc, clang]

alternative builds uhd:
  extends: .alternative builds
  rules:
    - if: $ON_SCHEDULE
      variables:
        CI_MERGE_REQUEST_LABELS: no-cache
  parallel:
    matrix:
      - os_type: ubuntu
        os_version: "22.04"
        compiler: [gcc, clang]
        uhd_version: "4.2.0.0"
      - os_type: ubuntu
        os_version: "20.04"
        compiler: [gcc, clang]
        uhd_version: ["4.2.0.0", "4.1.0.5"]

################################################################################
## Scheduler
################################################################################
.gnb-scheduler:
  stage: scheduler
  dependencies: []

scheduler-planer:
  extends:
    - .scheduler-planer
    - .gnb-scheduler
  rules:
    - if: $ON_MR
      changes:
        - .gitlab/ci/schedules.yml

scheduler:
  extends:
    - .scheduler
    - .gnb-scheduler
  rules:
    - if: $ON_DEFAULT_BRANCH

################################################################################
# Doc generation
################################################################################
requirements-report:
  stage: build and publish doc
  rules:
    - if: $ON_SCHEDULE
  image: registry.gitlab.com/softwareradiosystems/testing-tools/srs-tools:$SRS_TOOLS_VERSION
  script:
    - test-reporter --input unittests --output ./requirement_report.html
  dependencies: []
  artifacts:
    paths:
      - requirement_report.html

tests-report:
  stage: build and publish doc
  rules:
    - if: $ON_SCHEDULE
  image: python:3.9-alpine # sh entrypoint
  before_script:
    - pip install junit2html
  script:
    - junit2html xunit.xml ./test_report.html
  needs:
    - job: unit tests
      artifacts: true
  artifacts:
    paths:
      - test_report.html

pages:
  stage: build and publish doc
  rules:
    - if: $ON_SCHEDULE
  image: registry.gitlab.com/softwareradiosystems/testing-tools/doxygen:$DOCKER_DOXYGEN_VERSION
  script:
    - doxygen_generator.sh
    - mv build/public .
    - mv coverage_html public/
    - mv test_report.html public/
    - mv requirement_report.html public/
    - mv public/index.html public/index_doxygen.html
    - mv docs/index.html public/index.html
    - mv docs/*.png public/
    - sed -i 's/commit_hash/'$CI_COMMIT_SHA'/' public/index.html
  needs:
    - job: unit tests
      artifacts: true
    - job: requirements-report
      artifacts: true
    - job: tests-report
      artifacts: true
  artifacts:
    paths:
      - public

################################################################################
# Slack notification
################################################################################
.notifier:
  stage: notify status
  image: registry.gitlab.com/softwareradiosystems/testing-tools/srs-tools:$SRS_TOOLS_VERSION
  before_script:
    - |
      if [ -z ${SLACK_CHANNEL+x} ]; then
        echo "Variable SLACK_CHANNEL is unset"
        exit 1
      fi
    - MSG="Pipeline <${CI_PIPELINE_URL}|#${CI_PIPELINE_IID}> for commit <${CI_PROJECT_URL}/-/commit/${CI_COMMIT_SHA}|${CI_COMMIT_SHORT_SHA}> ${CI_COMMIT_BRANCH}${CI_COMMIT_TAG}."
  dependencies: []

success ci:
  extends: .notifier
  rules:
    - if: $ON_SCHEDULE == "true" && $NOTIFY_SLACK == "true"
  script:
    - notifier --title "$CI_PROJECT_NAME CI success" --msg "${MSG}" --level ok --channel "${SLACK_CHANNEL}" --token "${SLACK_TOKEN}"

failed ci:
  extends: .notifier
  rules:
    - if: $ON_SCHEDULE == "true" && $NOTIFY_SLACK == "true"
      when: on_failure
    - if: $ON_DEFAULT_BRANCH == "true"
      variables:
        SLACK_CHANNEL: "#ci_gnb"
      when: on_failure
  script:
    - notifier --title "$CI_PROJECT_NAME CI failed" --msg "${MSG}" --level fail --channel "${SLACK_CHANNEL}" --token "${SLACK_TOKEN}"
