include:
  - project: softwareradiosystems/testing-tools
    ref: "1.0.0"
    file: .gitlab/ci-shared/workflow.yml
  - project: softwareradiosystems/testing-tools
    ref: "1.0.0"
    file: .gitlab/ci-shared/scheduler.yml
  - local: .gitlab/ci/build.yml

stages:
  - static
  - build
  - unit tests
  - build and publish doc

## Static

code-format:
  stage: static
  rules:
    - if: $ON_MR
  variables:
    GIT_DEPTH: 0
  image: registry.gitlab.com/softwareradiosystems/testing-tools/static_validator:1.0.0
  before_script:
    - git remote set-branches --add origin $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - git fetch
  script:
    - run-clang-format-diff.sh origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME

## Build + Unit Tests

alternative builds:
  stage: build
  rules:
    - if: $ON_MR
    - if: $ON_DEFAULT_BRANCH
    - if: $ON_SCHEDULE
      variables:
        run_unit_tests: "true"
  needs: []
  trigger:
    include: .gitlab/ci/build.yml
    strategy: depend
  variables:
    run_unit_tests: "false"
  parallel:
    matrix:
      - os_type: ubuntu
        os_version: "22.04"
        compiler: clang
      - os_type: ubuntu
        os_version: "20.04"
        compiler: [gcc, clang]
      - os_type: archlinux
        os_version: latest
        compiler: [gcc, clang]

# Doc generation

pages:
  stage: build and publish doc
  rules:
    - if: $ON_DEFAULT_BRANCH
  variables:
    docker_version: "1.0.0"
  image: registry.gitlab.com/softwareradiosystems/testing-tools/doxygen:$docker_version
  script:
    - doxygen_generator.sh
    - mv build/public .
  artifacts:
    paths:
    - public
