include:
  - project: softwareradiosystems/testing-tools
    ref: "1.0.0"
    file: .gitlab/ci-shared/workflow.yml
  - project: softwareradiosystems/testing-tools
    ref: "1.0.0"
    file: .gitlab/ci-shared/scheduler.yml

variables:
  SCHEDULER_VERSION: "1.3.0"

stages:
  - static
  - launch build and test

code-format:
  stage: static
  rules:
    - if: $ON_MR
  variables:
    GIT_DEPTH: 0
  image: registry.gitlab.com/softwareradiosystems/testing-tools/static_validator:1.0.0
  before_script:
    - git remote set-branches --add origin $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - git fetch
  script:
    - run-clang-format-diff.sh origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME

build & test:
  stage: launch build and test
  rules:
    - if: $CI_MERGE_REQUEST_LABELS =~ /no-cache/
      variables:
        build_cache_mode: none    
    - if: $ON_MR
      variables:
        build_cache_mode: pull
    - if: $ON_DEFAULT_BRANCH
      variables:
        build_cache_mode: push
        report_failed_job: "true"
    - if: $ON_SCHEDULE
      variables:
        build_cache_mode: none
        report_failed_job: "true"
  needs: []
  trigger:
    include: .gitlab/ci/build.yml
    strategy: depend
  variables:
    docker_version: "1.0.0"
  parallel:
    matrix:
      - os_type: ubuntu
        os_version: "20.04"
        compiler: [gcc, clang]
      - os_type: ubuntu
        os_version: "22.04"
        compiler: clang
      - os_type: ubuntu
        os_version: "22.04"
        compiler: gcc
        run_unit_tests: "true"
      - os_type: archlinux
        os_version: latest
        compiler: [gcc, clang]
