[tool.pytest.ini_options]
log_cli = true
log_level = "INFO"
markers = [
  "smoke",
  "intensive",
]
minversion = "6.0"
python_files = [
  "tests/*.py",
]
render_collapsed = true

[tool.black]
line-length = 120

[tool.isort]
atomic = true
combine_as_imports = true
float_to_top = true
force_alphabetical_sort_within_sections = true
include_trailing_comma = true
line_length = 120
profile = "black"
remove_redundant_aliases = true
