ntn:
  cell_specific_koffset: 260
  ephemeris_info:
    pos_x: 23508375
    pos_y: 2211019
    pos_z: 22224489
    vel_x: 0
    vel_y: 0
    vel_z: 0

cell_cfg:
  sib:
    si_window_length: 5
    si_sched_info:
      - si_period: 16
        sib_mapping: 19
  pucch:
    sr_period_ms: 320
  csi:
    csi_rs_period: 80
  pdsch:
    max_nof_harq_retxs: 0
  prach:
    max_msg3_harq_retx: 0

cu_cp:
  rrc:
    rrc_procedure_timeout_ms: 12800
