#   This file contains the PUCCH configuration for the gNB to support:
#   - SR period 20ms
#   - CSI period 20ms or 40ms
#   - Max 32 UEs

cell_cfg:
  pucch:
    sr_period_ms: 20
    f1_nof_cell_res_sr: 50
    f2_nof_cell_res_csi: 50
  csi:
    csi_rs_period: 40  # This can be set either 20 or 40 ms.
  ul_common:
    max_ul_grants_per_slot: 64
    max_pucchs_per_slot: 63
  pusch:
    max_puschs_per_slot: 1
  tdd_ul_dl_cfg:
    nof_dl_symbols: 7
    nof_dl_slots: 7
    nof_ul_slots: 2