include:
  - project: softwareradiosystems/testing-tools
    ref: "1.0.0"
    file: .gitlab/ci-shared/workflow.yml
  - project: softwareradiosystems/testing-tools
    ref: "1.0.0"
    file: .gitlab/ci-shared/srs_tools.yml

variables:
  # Input variables
  os_type: ubuntu
  os_version: "22.04"
  compiler: gcc
  docker_version: "1.1.0"
  run_unit_tests: "true"

stages:
  - build
  - unit tests

.report_if_failed:
  image: registry.gitlab.com/softwareradiosystems/testing-tools/srs-builder-gnb-${os_type}-${os_version}:$docker_version
  variables:
    slack_notifier_version: "1.3.0"
  after_script:
    - !reference [.srs_tools_setup_job, before_script]
    - |
      if [[ $CI_JOB_STATUS = "failed" && $report_failed_job = "true" ]]; then
        srs_tools_setup $slack_notifier_version
        TITLE="$CI_JOB_NAME [$os_type $os_version $compiler] failed"
        MSG="<${CI_PROJECT_URL}/-/commit/${CI_COMMIT_SHA}|${CI_COMMIT_SHORT_SHA}> ${CI_COMMIT_BRANCH}${CI_COMMIT_TAG}. Check the <${CI_JOB_URL}|log>."
        notifier --title "${TITLE}" --msg "${MSG}" --level fail --channel "##ci_gnb" --token "${SLACK_TOKEN}"
      fi

# Build

.build:
  stage: build
  extends: .report_if_failed
  needs: []
  script:
    - |
      if [ $run_unit_tests = "true" ]; then
        EXTRA_BUILD_ARGS="-DENABLE_GCOV=True"
      fi
    - builder.sh -c $compiler $EXTRA_BUILD_ARGS .
  cache: &build_cache
    key: ${os_type}-${os_version}-${docker_version}-${compiler}
    paths:
      - ccache
  artifacts: &build_artifacts
    paths:
      - build/CTestTestfile.cmake
      - build/unittests
      - build/apps/cu-up/cu-up

build [cached]:
  # The job will use the cache for latest compilation
  extends: .build
  rules:
    - if: $CI_MERGE_REQUEST_LABELS =~ /no-cache/
      when: never
    - if: $ON_MR == "true"
  variables:
    report_failed_job: "false"
  cache:
    <<: *build_cache
    policy: pull
  artifacts:
    <<: *build_artifacts
    expire_in: 10 minutes

build [clean and update cache]:
  # A clean build will be done and the job will push a new fresh cache
  extends: .build
  rules:
    - if: $ON_DEFAULT_BRANCH
  variables:
    report_failed_job: "true"
  cache:
    <<: *build_cache
    policy: push
  artifacts:
    <<: *build_artifacts
    expire_in: 6 hours

build [clean]:
  # Fresh build with no interacton with the cache
  extends: .build
  rules:
    - if: $CI_MERGE_REQUEST_LABELS =~ /no-cache/
    - if: $ON_SCHEDULE
  variables:
    report_failed_job: "true"
  cache: []
  artifacts:
    <<: *build_artifacts
    expire_in: 7 days

# Unit tests

unit test:
  stage: unit tests
  extends: .report_if_failed
  rules:
    - if: $run_unit_tests == "true"
  script:
    # Tests
    - cd build
    - ctest -j "$(nproc --all)" --schedule-random --output-junit xunit.xml
    # Code coverage
    - GCOVR_ARGS="--exclude-unreachable-branches --root ${CI_PROJECT_DIR}"
    - gcovr --xml-pretty --print-summary $GCOVR_ARGS -o coverage.xml
    # Generate coverage html
    # - mkdir coverage
    # - gcovr --html --html-details        $GCOVR_ARGS -o coverage/index.html
  coverage: /^\s*lines:\s*\d+.\d+\%/
  artifacts:
    reports:
      junit: build/xunit.xml
      coverage_report:
        coverage_format: cobertura
        path: build/coverage.xml
    # Save coverage html
    # paths:
    #   - build/coverage/*
