include:
  - project: softwareradiosystems/testing-tools
    ref: "16"
    file: .gitlab/ci-shared/default.yml
  - project: softwareradiosystems/testing-tools
    ref: "16"
    file: .gitlab/ci-shared/workflow.yml
  - project: softwareradiosystems/testing-tools
    ref: "16"
    file: .gitlab/ci-shared/versions.yml

variables:
  # Input variables
  # General
  os_type: ubuntu
  os_version: "22.04"
  docker_version: $DOCKER_BUILDER_VERSION
  # Build
  compiler: gcc
  uhd_version: "4.1.0.5"
  check_flags: "true"
  # Tests
  run_tests: "true"
  enable_coverage: "true"
  coverage_full_report: $ON_SCHEDULE

stages:
  - build
  - tests
  - documentation

.build_and_unit:
  image: registry.gitlab.com/softwareradiosystems/testing-tools/srs-builder-gnb-${os_type}-${os_version}:$docker_version
  tags:
    - srs-rfci-docker

################################################################################
# Build
################################################################################

.build:
  stage: build
  extends: .build_and_unit
  needs: []
  script:
    - |
      if [ $enable_coverage = "true" ]; then
        EXTRA_BUILD_ARGS="-DENABLE_GCOV=True"
      fi
    - builder.sh -c $compiler -u $uhd_version -DASSERT_LEVEL=PARANOID $EXTRA_BUILD_ARGS .
  cache: &build_cache
    key: ${os_type}-${os_version}-${docker_version}-${compiler}
    paths:
      - ccache
  artifacts:
    paths:
      # Binaries
      - build/apps/cu-up/cu-up
      # Ctest
      - build/CTestTestfile.cmake
      - build/unittests
      - build/integrationtests
      - build/**/*.gcno
    expire_in: 10 minutes

build [cached]:
  # The job will use the cache for latest compilation
  extends: .build
  rules:
    - if: $CI_MERGE_REQUEST_LABELS =~ /no-cache/
      when: never
    - if: $ON_MR
  cache:
    <<: *build_cache
    policy: pull

build [clean and update cache]:
  # A clean build will be done and the job will push a new fresh cache
  extends: .build
  rules:
    - if: $CI_MERGE_REQUEST_LABELS =~ /no-cache/
      when: never
    - if: $ON_SCHEDULE
  cache:
    <<: *build_cache
    policy: push

build [clean]:
  # Fresh build with no interacton with the cache
  extends: .build
  rules:
    - if: $CI_MERGE_REQUEST_LABELS =~ /no-cache/
  cache: []

cmake flag check:
  stage: build
  extends: .build_and_unit
  rules:
    - if: $ON_DEFAULT_BRANCH
      when: never
    - if: $check_flags == "true"
  script:
    - CC=/usr/bin/gcc
    - CXX=/usr/bin/g++
    - mkdir build && cd build && cmake -G Ninja ${flag} ..
  parallel:
    matrix:
      - flag:
          [
            -DSTOP_ON_WARNING=True,
            -DENABLE_TSAN=True,
            -DENABLE_ASAN=True,
            -DENABLE_EXPORT=True,
            -DBUILD_TESTS=False,
          ]
  dependencies: []

################################################################################
# Test execution
################################################################################

.ctest:
  stage: tests
  extends: .build_and_unit
  rules:
    - if: $ON_DEFAULT_BRANCH
      when: never
    - if: $run_tests == "true"
  needs:
    - job: build [cached]
      artifacts: true
      optional: true
    - job: build [clean and update cache]
      artifacts: true
      optional: true
    - job: build [clean]
      artifacts: true
      optional: true
  variables:
    test_folder: ""
  script:
    # Launch ctest
    - cd build/${test_folder}
    - ctest -j "$(nproc --all)" --schedule-random --output-on-failure --output-junit xunit.xml && ret=0 || ret=1
    # Launch coverage
    - cd ${CI_PROJECT_DIR}/build
    - |
      if [ $enable_coverage = "true" ]; then
        gcovr --xml --print-summary -j "$(nproc --all)" --exclude-unreachable-branches \
          --exclude-directories unittests \
          --exclude-directories integrationtests  \
          --exclude-directories benchmarks \
          --exclude-directories apps/examples \
          --exclude "${CI_PROJECT_DIR}/include/srsgnb/asn1/e1ap.h" \
          --exclude "${CI_PROJECT_DIR}/include/srsgnb/asn1/f1ap.h" \
          --exclude "${CI_PROJECT_DIR}/include/srsgnb/asn1/rrc_nr/.*" \
          --exclude "${CI_PROJECT_DIR}/lib/asn1/e1ap.cpp" \
          --exclude "${CI_PROJECT_DIR}/lib/asn1/f1ap.cpp" \
          --exclude "${CI_PROJECT_DIR}/lib/asn1/ngap.cpp" \
          --exclude "${CI_PROJECT_DIR}/lib/asn1/rrc_nr/.*" \
          --exclude-lines-by-pattern ".*srsgnb_assert.*|.*srsgnb_sanity_check.*" \
          --root ${CI_PROJECT_DIR} -o coverage.xml

        filesize=$(stat -c%s coverage.xml)
        maxsize=$((10*1204*1024))
        (( filesize > maxsize )) && echo "coverage.xml is greater than 10MB, over gitlab limit" && exit 1
      fi
    - exit $ret
  after_script:
    # Move files to upload to root so no intermiddle folders will be created in the artifact
    - mv ${CI_PROJECT_DIR}/build/${test_folder}/xunit.xml ${CI_PROJECT_DIR}/${CI_JOB_ID}_xunit.xml
    - mv ${CI_PROJECT_DIR}/build/coverage.xml             ${CI_PROJECT_DIR}/${CI_JOB_ID}_coverage.xml
  artifacts:
    when: always
    reports:
      junit: ${CI_JOB_ID}_xunit.xml
      coverage_report:
        coverage_format: cobertura
        path: ${CI_JOB_ID}_coverage.xml
    paths:
      - ${CI_JOB_ID}_xunit.xml
      - ${CI_JOB_ID}_coverage.xml
    expire_in: 10 minutes

unit tests:
  extends: .ctest
  variables:
    test_folder: unittests

integration tests:
  extends: .ctest
  variables:
    test_folder: integrationtests

################################################################################
# Test report
################################################################################

unit coverage:
  image:
    name: jorturfer/report-generator
    entrypoint: ["/bin/sh", "-c"]
  stage: documentation
  rules:
    - if: $ON_DEFAULT_BRANCH
      when: never
    - if: $run_tests == "true" && $enable_coverage == "true"
      when: always # Even if previous stages/required jobs fail
  before_script:
    - PACKAGE_URL=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/coverage/${CI_COMMIT_BRANCH}${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}/coverage_history.tar.gz
    # Download coverage history from the registry
    - |
      download_from_registry() {
        apk add --update curl

        cd ${CI_PROJECT_DIR}
        http_code=$(curl -w "%{http_code}" --header "PRIVATE-TOKEN: $CODEBOT_TOKEN" "${PACKAGE_URL}" -o output.tar.gz)
        if [[ $http_code == "200" ]]; then
          tar -xf output.tar.gz
        fi
      }
    # Publish coverage history folder to the registry
    - |
      publish_to_registry() {
        cd ${CI_PROJECT_DIR}
        tar -czf coverage_history.tar.gz coverage_history
        curl --fail --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file coverage_history.tar.gz "${PACKAGE_URL}"
      }
  script:
    - |
      if [[ $coverage_full_report && $coverage_full_report = "true" ]]; then
        download_from_registry
        HTML_TYPE=Html
        HISTORY=-historydir:coverage_history
      else
        HTML_TYPE=HtmlSummary
        HISTORY=
      fi
    - |
      /app/ReportGenerator -reports:*coverage.xml -targetdir:coverage_html ${HISTORY} \
        -title:${CI_PROJECT_NAME} -tag:${CI_COMMIT_SHA} \
        -reporttypes:"${HTML_TYPE};TextSummary"
    - cat coverage_html/Summary.txt
    - |
      if [[ $coverage_full_report && $coverage_full_report = "true" ]]; then
        publish_to_registry
      fi
  coverage: /^\s*Line coverage:\s*\d+.\d+\%/
  needs:
    - job: unit tests
      artifacts: true
  artifacts:
    paths:
      - coverage_html
    expire_in: 10 minutes
